image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_STRATEGY: fetch
  GIT_DEPTH: 1

cache:
  paths:
    - .cache/pip
    - venv/

pages:
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install markdown
    - make -j 3
    - mkdir -p public
    - cp -u *.svg *.css *.js index.html public
    - for dir in */ ; do [[ $dir == public/ ]] || mkdir -p public/$dir; done
    - for dir in */ ; do [[ $dir == public/ ]] || cp -u ${dir}*.{png,html} public/$dir; done
    - ls -l /usr/local/bin
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - index.html
  artifacts:
    paths:
      - public
