image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_STRATEGY: fetch
  GIT_DEPTH: 2

cache:
  paths:
    - .cache/pip
    - venv

pages:
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install markdown
    - pip install markdown-checklist
    - make -j 3
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - index.html
        - .gitlab-ci.yml
        - src/*.html
        - src/**/*.md
  artifacts:
    paths:
      - public
