image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_STRATEGY: fetch
  GIT_DEPTH: 1

cache:
  paths:
    - .cache/pip
    - venv
    - public

pages:
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install markdown
    - make -j 3
    - ls -l /usr/local/bin
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - index.html
        - .gitlab-ci.yml
  artifacts:
    paths:
      - public
