image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache: {}

pages:
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install markdown
    - pip install pygments
    - mkdir -p public
    - cp -ru Makefile *.sed *.svg *.css *.html *.js public
    - for dir in */; do [[ $dir == public/ ]] || cp -ru $dir public; done
    - cd public
    - make
  artifacts:
    paths:
      - public
  only:
    - main
  # rules:
  #   - if: '$(( $CI_JOB_ID % 5 - 1 )) == 0'
